# Generated by Django 4.1.7 on 2023-03-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestballapp', '0002_remove_session_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='players',
            field=models.ManyToManyField(related_name='games', to='bestballapp.player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='putts',
            field=models.IntegerField(default=0),
        ),
    ]
