# Generated by Django 4.1.7 on 2023-04-01 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bestballapp', '0003_session_players_alter_player_name_alter_player_putts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ball',
            name='currentPlayer',
        ),
        migrations.AddField(
            model_name='ball',
            name='lastSpin',
            field=models.DecimalField(decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='currentBall',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bestballapp.ball'),
        ),
        migrations.AlterField(
            model_name='ball',
            name='distanceFromHole',
            field=models.DecimalField(decimal_places=3, default=100, max_digits=8),
        ),
    ]
